import { msg } from '@lingui/core/macro'
import type { MessageDescriptor } from '@lingui/core'

/**
 * Countries offered anywhere a member says where they are.
 *
 * Plain English names, not codes: `profiles.country` is TEXT and has always
 * held the name, so a code here would orphan every profile already saved. The
 * spellings for the OECS and Caribbean entries match the `countries` table
 * seeded in migration 058 exactly, because the same country must not read two
 * ways depending on which form a member filled in.
 *
 * Grouped rather than one A–Z run. This is an OECS platform: a member from
 * Saint Lucia should not scroll past Kazakhstan to find home, and the ordering
 * is the same courtesy the employer and institution forms already extend by
 * sorting the DB table on `sort_order`.
 */

/** OECS member states and associate members. */
export const OECS_COUNTRIES = [
  'Antigua and Barbuda',
  'Anguilla',
  'British Virgin Islands',
  'Dominica',
  'Grenada',
  'Guadeloupe',
  'Martinique',
  'Montserrat',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
] as const

/** The rest of the Caribbean, including the CARICOM mainland states. */
export const WIDER_CARIBBEAN_COUNTRIES = [
  'Aruba',
  'Bahamas',
  'Barbados',
  'Belize',
  'Bermuda',
  'Cayman Islands',
  'Cuba',
  'Curaçao',
  'Dominican Republic',
  'Guyana',
  'Haiti',
  'Jamaica',
  'Puerto Rico',
  'Sint Maarten',
  'Suriname',
  'Trinidad and Tobago',
  'Turks and Caicos Islands',
  'United States Virgin Islands',
] as const

/** Everywhere else, alphabetically. */
export const OTHER_COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Greenland',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const

export interface CountryGroup {
  label: MessageDescriptor
  countries: readonly string[]
}

/**
 * The optgroups, in the order they are shown. Only the three headings are
 * translated: country names are proper nouns, and running two hundred of them
 * through the catalogues would cost every translator a day to change nothing.
 */
export const COUNTRY_GROUPS: readonly CountryGroup[] = [
  { label: msg`OECS member states`, countries: OECS_COUNTRIES },
  { label: msg`Wider Caribbean`, countries: WIDER_CARIBBEAN_COUNTRIES },
  { label: msg`All other countries`, countries: OTHER_COUNTRIES },
]

/** Every offered country, flat. Used to spot a stored value we no longer list. */
export const ALL_COUNTRIES: readonly string[] = COUNTRY_GROUPS.flatMap((g) => [...g.countries])
