/// <reference types="vite/client" />

/**
 * Generated by scripts/optimize-images.mjs and served by
 * vite/image-manifest-plugin.mjs. Resolves to an empty manifest when the
 * generator has not run, so this always type-checks on a clean checkout.
 */
declare module 'virtual:image-manifest' {
  import type { ImageManifest } from './lib/image-variants'
  const manifest: ImageManifest
  export default manifest
}
