import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { shouldTranslate } from '../i18n/should-translate'
// @ts-expect-error — a plain .mjs config with no types; this file is excluded
// from tsconfig.app.json, so it never reaches tsc.
import { globToRegExp } from '../../../scripts/i18n/config.mjs'

/**
 * Invariants the extraction toolchain depends on.
 *
 * The scanner, the codemod and the CI ratchet are plain Node scripts, so nothing
 * else type-checks or exercises them. These are the properties whose violation
 * would be silent — a manifest that no longer matches the code, a catalog full
 * of slugs, a ratchet guarding nothing — rather than loud.
 */

const root = process.cwd()
const read = (p: string) => readFileSync(resolve(root, p), 'utf8')

describe('the harvested catalog', () => {
  const path = 'src/i18n/harvested.ts'

  it('exists — without it, ~1,000 strings in the pure-data modules are invisible to lingui extract', () => {
    expect(existsSync(resolve(root, path))).toBe(true)
  })

  it('contains only strings the shared predicate accepts', () => {
    // The harvester applies shouldTranslate before writing. If a slug ever lands
    // here it goes straight into the catalogs and gets paid for, so this is
    // checked against the real predicate rather than trusted.
    const source = read(path)
    const messages = [...source.matchAll(/^ {2}msg`([\s\S]*?)`,$/gm)].map((m) =>
      m[1].replace(/\\`/g, '`').replace(/\\\$\{/g, '${').replace(/\\\\/g, '\\')
    )

    expect(messages.length).toBeGreaterThan(500)

    const rejected = messages.filter((m) => !shouldTranslate(m))
    expect(rejected).toEqual([])
  })

  it('is generated, and says so', () => {
    // Someone will eventually open it and start editing. The banner is the only
    // thing standing between that and a silently reverted harvest.
    expect(read(path)).toContain('GENERATED by scripts/i18n/harvest.mjs')
  })
})

describe('the message catalogs', () => {
  const locales = ['en', 'fr', 'es'] as const

  it.each(locales)('%s catalog exists', (locale) => {
    expect(existsSync(resolve(root, `src/locales/${locale}/messages.po`))).toBe(true)
  })

  it('fr and es carry the same message ids as the English source', () => {
    // A target catalog that has drifted from the source silently renders English
    // for whatever it is missing, and the missing entries never show up anywhere.
    const ids = (locale: string) =>
      new Set([...read(`src/locales/${locale}/messages.po`).matchAll(/^msgid "(.*)"$/gm)].map((m) => m[1]))

    const en = ids('en')
    for (const locale of ['fr', 'es']) {
      expect([...ids(locale)].sort()).toEqual([...en].sort())
    }
  })

  it('keeps every ICU placeholder intact in the translations', () => {
    // `Hello {name}` translated to `Bonjour {nom}` renders the literal text
    // "{nom}" to a reader. The translation script checks this and refuses to
    // write a mismatch; this is the assertion that the check is working.
    const TAG = /<\/?\d+>/g

    /**
     * Argument names only, at brace depth 0.
     *
     * A flat `/\{[^}]+\}/` cannot read a plural — it splits
     * `{n, plural, one {# person} other {# people}}` into two bogus tokens — so
     * it reported every correctly translated plural as a mismatch. The branch
     * BODIES are supposed to differ between languages, and so is the number of
     * branches: French and Spanish do not share English's plural categories.
     */
    const signature = (text: string) => {
      const names: string[] = []
      let depth = 0
      for (let i = 0; i < text.length; i++) {
        if (text[i] === '}') {
          depth = Math.max(0, depth - 1)
          continue
        }
        if (text[i] !== '{') continue
        if (depth === 0) {
          let j = i + 1
          while (j < text.length && text[j] !== ',' && text[j] !== '}') j++
          names.push(text.slice(i + 1, j).trim())
        }
        depth++
      }
      return [...names.sort(), ...(text.match(TAG) ?? []).sort()]
    }

    for (const locale of ['fr', 'es']) {
      const text = read(`src/locales/${locale}/messages.po`)
      const pairs = [...text.matchAll(/^msgid "(.*)"\nmsgstr "(.*)"$/gm)]
      expect(pairs.length).toBeGreaterThan(0)

      for (const [, msgid, msgstr] of pairs) {
        if (!msgstr) continue // untranslated falls back to English — fine
        expect(
          signature(msgstr),
          `${locale}: placeholders changed in ${JSON.stringify(msgid)}`
        ).toEqual(signature(msgid))
      }
    }
  })
})

describe('the codemod glob', () => {
  /**
   * A glob that silently matches nothing is the worst failure this toolchain
   * has. `--glob 'src/components/ui/**'` printed "No auto entries match" and
   * exited 0, which reads exactly like "that slice is already done" — the
   * trailing `**` had compiled to `(?:.*\/)?`, which requires the path to end in
   * a slash, so it matched directories and never files.
   */
  const cases: [string, string, boolean][] = [
    // A trailing ** is the form every slice command uses.
    ['src/components/ui/**', 'src/components/ui/Modal.tsx', true],
    ['src/components/ui/**', 'src/components/ui/nested/Modal.tsx', true],
    ['src/components/ui/**', 'src/components/layout/Navbar.tsx', false],
    // ** between segments spans zero or more directories, not one or more.
    ['src/**/*.tsx', 'src/App.tsx', true],
    ['src/**/*.tsx', 'src/pages/events/EventsPage.tsx', true],
    ['src/**/*.tsx', 'src/pages/events/hooks.ts', false],
    // A single star stays inside its segment.
    ['src/*.ts', 'src/main.ts', true],
    ['src/*.ts', 'src/lib/utils.ts', false],
  ]

  it.each(cases)('%s vs %s -> %s', (glob, path, expected) => {
    expect(globToRegExp(glob).test(path)).toBe(expected)
  })
})

describe('no source file carries a raw NUL byte', () => {
  /**
   * Two got in — a sentinel in the codemod's glob compiler, and a field-key
   * separator in useTranslated.ts. Both worked. Both also made `grep` report the
   * file as binary, vanished from every diff viewer, and did not survive being
   * edited. The separator character is the right choice; writing it as a literal
   * byte is not.
   */
  const NUL = String.fromCharCode(0)
  const EXTENSIONS = /\.(ts|tsx|mjs|js|sql|css|json)$/
  const SKIP = new Set(['node_modules', '.git', 'dist', 'dev-dist', 'coverage'])

  function* sourceFiles(dir: string): Generator<string> {
    for (const entry of readdirSync(resolve(root, dir))) {
      if (SKIP.has(entry)) continue
      const rel = join(dir, entry)
      if (statSync(resolve(root, rel)).isDirectory()) yield* sourceFiles(rel)
      else if (EXTENSIONS.test(entry)) yield rel
    }
  }

  it.each(['src', 'scripts', 'api', 'supabase'])('%s is clean', (dir) => {
    const offenders = [...sourceFiles(dir)].filter((f) => read(f).includes(NUL))
    expect(offenders).toEqual([])
  })
})

describe('the ratchet is actually guarding something', () => {
  it('lists every file the shell slice migrated', () => {
    // MIGRATED_PATHS is what makes i18n:check anything other than a no-op. A
    // slice that lands without its entry is a directory that can quietly refill
    // with English.
    const config = read('scripts/i18n/config.mjs')
    // Directories, not files. A slice guards its whole directory so that a
    // component added later cannot ship with unwrapped copy — which is the
    // difference between a migration that finishes and one that does not.
    for (const file of [
      'src/components/ui/',
      'src/components/layout/',
      'src/components/projects/ProjectCard.tsx',
    ]) {
      expect(config).toContain(file)
    }
  })

  it('keeps admin out of scope in both the config and the lingui catalog', () => {
    // Agreed out of scope. If the two disagree, the extractor pulls in ~21k
    // lines of staff-only copy that nobody will ever translate, and every
    // "missing" count becomes meaningless.
    expect(read('scripts/i18n/config.mjs')).toContain('src/pages/admin/')
    expect(read('lingui.config.ts')).toContain('src/pages/admin/**')
  })

  it('keeps the Sentry developer strings out of both', () => {
    expect(read('scripts/i18n/config.mjs')).toContain('src/lib/app-error.ts')
    expect(read('lingui.config.ts')).toContain('src/lib/app-error.ts')
  })
})
