import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * Every public-root asset path written as a string literal in src/ must exist
 * on disk.
 *
 * This is the guardrail for a whole class of bug that nothing else catches:
 * `/ktip-logo-nobg.webp` was referenced from two components for months and
 * 404'd in both, because a public/ path is just a string — the compiler never
 * sees it, and the image only fails at runtime, silently, as a blank box.
 *
 * The scan is deliberately repo-wide rather than a hand-kept list. A list would
 * have to be updated by the same person who just typo'd the path.
 *
 * Lives under __tests__ rather than beside hero-images.ts because it reads the
 * filesystem: tsconfig.app.json has no node types, so a test importing node:fs
 * has to be typechecked by tsconfig.node.json instead.
 */

const SRC = resolve(process.cwd(), 'src')
const PUBLIC = resolve(process.cwd(), 'public')

// Root-relative, ends in an image extension, no interpolation or spaces. That
// last part matters: `${base}/x.webp` is resolved at runtime and can't be
// checked here, so it must not be mistaken for a literal.
const ASSET_REF = /['"`](\/[A-Za-z0-9_\-./]+\.(?:webp|avif|png|jpe?g|svg))['"`]/g

// Generated by scripts/optimize-images.mjs and gitignored, so it is legitimately
// absent on a clean checkout and after `git clean`. Asserting these exist would
// make the suite depend on whether the generator had been run, which is exactly
// the kind of environment-dependent failure this file exists to avoid.
const GENERATED = /^\/_img\//

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) return sourceFiles(path)
    return /\.tsx?$/.test(entry) ? [path] : []
  })
}

function collectReferences() {
  const refs = new Map<string, string[]>()
  for (const file of sourceFiles(SRC)) {
    // Test fixtures reference deliberately fake CDNs and placeholder art.
    if (/\.test\.tsx?$/.test(file)) continue
    const text = readFileSync(file, 'utf8')
    for (const [, path] of text.matchAll(ASSET_REF)) {
      if (GENERATED.test(path)) continue
      const seenIn = refs.get(path) ?? []
      seenIn.push(file.slice(SRC.length + 1).replace(/\\/g, '/'))
      refs.set(path, seenIn)
    }
  }
  return refs
}

describe('public asset references', () => {
  const refs = collectReferences()

  it('finds asset paths to check', () => {
    // Guards the guard: if the regex or the walk breaks, the suite would
    // otherwise pass by checking nothing at all.
    expect(refs.size).toBeGreaterThan(30)
  })

  it('resolves every referenced path to a file in public/', () => {
    const missing = [...refs.entries()]
      .filter(([path]) => !existsSync(join(PUBLIC, path)))
      .map(([path, files]) => `${path} <- ${files.join(', ')}`)

    expect(missing).toEqual([])
  })
})
